INSERT INTO countries (name, code, description) VALUES ('Vietnam', 'VN', 'Quốc gia Đông Nam Á với thủ đô Hà Nội');
INSERT INTO countries (name, code, description) VALUES ('United States', 'US', 'Hợp chủng quốc Hoa Kỳ, nền kinh tế lớn nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('Japan', 'JP', 'Đất nước mặt trời mọc, nổi tiếng với công nghệ và văn hóa anime');
INSERT INTO countries (name, code, description) VALUES ('France', 'FR', 'Quốc gia châu Âu nổi tiếng với rượu vang và tháp Eiffel');
INSERT INTO countries (name, code, description) VALUES ('Germany', 'DE', 'Cường quốc công nghiệp hàng đầu châu Âu');
INSERT INTO countries (name, code, description) VALUES ('China', 'CN', 'Quốc gia đông dân nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('South Korea', 'KR', 'Xứ sở kim chi và công nghệ hàng đầu châu Á');
INSERT INTO countries (name, code, description) VALUES ('United Kingdom', 'UK', 'Liên hiệp Vương quốc Anh và Bắc Ireland');
INSERT INTO countries (name, code, description) VALUES ('Italy', 'IT', 'Quốc gia của pizza, thời trang và di sản La Mã');
INSERT INTO countries (name, code, description) VALUES ('Canada', 'CA', 'Quốc gia có diện tích lớn thứ hai thế giới');
INSERT INTO countries (name, code, description) VALUES ('Australia', 'AU', 'Lục địa và quốc gia duy nhất, nổi tiếng với kangaroo');
INSERT INTO countries (name, code, description) VALUES ('India', 'IN', 'Quốc gia Nam Á có dân số đông thứ hai thế giới');
INSERT INTO countries (name, code, description) VALUES ('Brazil', 'BR', 'Quốc gia Nam Mỹ nổi tiếng với lễ hội Carnival');
INSERT INTO countries (name, code, description) VALUES ('Russia', 'RU', 'Quốc gia có diện tích lớn nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('Spain', 'ES', 'Quốc gia nổi tiếng với bóng đá và món tapas');
INSERT INTO countries (name, code, description) VALUES ('Sweden', 'SE', 'Quốc gia Bắc Âu nổi tiếng với IKEA và Spotify');
INSERT INTO countries (name, code, description) VALUES ('Norway', 'NO', 'Quốc gia Bắc Âu với thiên nhiên hùng vĩ và phúc lợi cao');
INSERT INTO countries (name, code, description) VALUES ('Denmark', 'DK', 'Vương quốc nhỏ ở Bắc Âu, hạnh phúc nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('Finland', 'FI', 'Đất nước của nghìn hồ và thương hiệu Nokia');
INSERT INTO countries (name, code, description) VALUES ('Netherlands', 'NL', 'Xứ sở hoa tulip và cối xay gió');
INSERT INTO countries (name, code, description) VALUES ('Switzerland', 'CH', 'Trung tâm tài chính và đồng hồ nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Belgium', 'BE', 'Nổi tiếng với sô-cô-la và bia ngon');
INSERT INTO countries (name, code, description) VALUES ('Austria', 'AT', 'Quốc gia Trung Âu nổi tiếng với âm nhạc cổ điển');
INSERT INTO countries (name, code, description) VALUES ('Poland', 'PL', 'Quốc gia Trung Âu có lịch sử phong phú');
INSERT INTO countries (name, code, description) VALUES ('Czech Republic', 'CZ', 'Đất nước của bia và lâu đài cổ');
INSERT INTO countries (name, code, description) VALUES ('Hungary', 'HU', 'Thủ đô Budapest nổi tiếng với suối nước nóng');
INSERT INTO countries (name, code, description) VALUES ('Portugal', 'PT', 'Quốc gia ven biển với món rượu vang nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Greece', 'GR', 'Cái nôi của nền văn minh phương Tây');
INSERT INTO countries (name, code, description) VALUES ('Turkey', 'TR', 'Giao điểm của châu Âu và châu Á');
INSERT INTO countries (name, code, description) VALUES ('Saudi Arabia', 'SA', 'Trung tâm Hồi giáo và quốc gia dầu mỏ lớn nhất');
INSERT INTO countries (name, code, description) VALUES ('United Arab Emirates', 'AE', 'Quốc gia giàu có với thành phố Dubai nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Israel', 'IL', 'Quốc gia Trung Đông có nền công nghệ phát triển');
INSERT INTO countries (name, code, description) VALUES ('Egypt', 'EG', 'Đất nước của kim tự tháp và sông Nile');
INSERT INTO countries (name, code, description) VALUES ('South Africa', 'ZA', 'Quốc gia đầu tàu của châu Phi');
INSERT INTO countries (name, code, description) VALUES ('Nigeria', 'NG', 'Quốc gia đông dân nhất châu Phi');
INSERT INTO countries (name, code, description) VALUES ('Kenya', 'KE', 'Quốc gia nổi tiếng với safari và vận động viên marathon');
INSERT INTO countries (name, code, description) VALUES ('Argentina', 'AR', 'Quốc gia Nam Mỹ với bóng đá và thịt bò ngon');
INSERT INTO countries (name, code, description) VALUES ('Chile', 'CL', 'Đất nước dài nhất Nam Mỹ với khí hậu đa dạng');
INSERT INTO countries (name, code, description) VALUES ('Peru', 'PE', 'Quê hương của nền văn minh Inca');
INSERT INTO countries (name, code, description) VALUES ('Colombia', 'CO', 'Nổi tiếng với cà phê và âm nhạc salsa');
INSERT INTO countries (name, code, description) VALUES ('Mexico', 'MX', 'Đất nước của taco, tequila và văn hóa Aztec');
INSERT INTO countries (name, code, description) VALUES ('Thailand', 'TH', 'Đất nước chùa vàng và du lịch phát triển');
INSERT INTO countries (name, code, description) VALUES ('Malaysia', 'MY', 'Quốc gia Đông Nam Á đa văn hóa');
INSERT INTO countries (name, code, description) VALUES ('Singapore', 'SG', 'Quốc gia nhỏ nhưng giàu có và sạch đẹp');
INSERT INTO countries (name, code, description) VALUES ('Philippines', 'PH', 'Quốc gia quần đảo với hơn 7.000 hòn đảo');
INSERT INTO countries (name, code, description) VALUES ('Indonesia', 'ID', 'Quốc gia vạn đảo, đông dân thứ tư thế giới');
INSERT INTO countries (name, code, description) VALUES ('Laos', 'LA', 'Quốc gia Đông Nam Á hiền hòa');
INSERT INTO countries (name, code, description) VALUES ('Cambodia', 'KH', 'Quốc gia có Angkor Wat nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Myanmar', 'MM', 'Quốc gia Đông Nam Á với nền văn hóa Phật giáo đặc trưng');
INSERT INTO countries (name, code, description) VALUES ('Nepal', 'NP', 'Quốc gia có đỉnh Everest cao nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('Bhutan', 'BT', 'Quốc gia đo hạnh phúc bằng chỉ số GNH');
INSERT INTO countries (name, code, description) VALUES ('Pakistan', 'PK', 'Quốc gia Nam Á có nền văn hóa Hồi giáo');
INSERT INTO countries (name, code, description) VALUES ('Bangladesh', 'BD', 'Quốc gia đông dân với ngành dệt may lớn mạnh');
INSERT INTO countries (name, code, description) VALUES ('Sri Lanka', 'LK', 'Hòn ngọc Ấn Độ Dương với văn hóa lâu đời');
INSERT INTO countries (name, code, description) VALUES ('New Zealand', 'NZ', 'Đất nước của những chú cừu và phong cảnh đẹp như phim');
INSERT INTO countries (name, code, description) VALUES ('Iceland', 'IS', 'Quốc gia của băng và lửa');
INSERT INTO countries (name, code, description) VALUES ('Ireland', 'IE', 'Quốc gia xanh với văn hóa nhạc dân gian đặc sắc');
INSERT INTO countries (name, code, description) VALUES ('Scotland', 'SC', 'Vùng đất của whisky và lâu đài cổ');
INSERT INTO countries (name, code, description) VALUES ('Wales', 'WL', 'Vùng đất của rồng đỏ và phong cảnh hoang sơ');
INSERT INTO countries (name, code, description) VALUES ('Luxembourg', 'LU', 'Quốc gia nhỏ giàu có ở châu Âu');
INSERT INTO countries (name, code, description) VALUES ('Monaco', 'MC', 'Thiên đường thuế và sòng bạc Monte Carlo');
INSERT INTO countries (name, code, description) VALUES ('Liechtenstein', 'LI', 'Quốc gia nhỏ giữa Thụy Sĩ và Áo');
INSERT INTO countries (name, code, description) VALUES ('Croatia', 'HR', 'Quốc gia có đường bờ biển đẹp ở Địa Trung Hải');
INSERT INTO countries (name, code, description) VALUES ('Slovenia', 'SI', 'Quốc gia nhỏ nhưng phát triển ở châu Âu');
INSERT INTO countries (name, code, description) VALUES ('Slovakia', 'SK', 'Đất nước Trung Âu với phong cảnh đẹp');
INSERT INTO countries (name, code, description) VALUES ('Romania', 'RO', 'Quê hương của truyền thuyết Dracula');
INSERT INTO countries (name, code, description) VALUES ('Bulgaria', 'BG', 'Quốc gia Balkan cổ xưa');
INSERT INTO countries (name, code, description) VALUES ('Serbia', 'RS', 'Quốc gia Đông Âu với nền văn hóa phong phú');
INSERT INTO countries (name, code, description) VALUES ('Ukraine', 'UA', 'Quốc gia lớn thứ hai châu Âu');
INSERT INTO countries (name, code, description) VALUES ('Belarus', 'BY', 'Quốc gia Đông Âu với nền công nghiệp mạnh');
INSERT INTO countries (name, code, description) VALUES ('Estonia', 'EE', 'Quốc gia kỹ thuật số hàng đầu châu Âu');
INSERT INTO countries (name, code, description) VALUES ('Latvia', 'LV', 'Quốc gia vùng Baltic nhỏ xinh');
INSERT INTO countries (name, code, description) VALUES ('Lithuania', 'LT', 'Quốc gia Baltic có lịch sử độc lập mạnh mẽ');
INSERT INTO countries (name, code, description) VALUES ('Morocco', 'MA', 'Quốc gia Bắc Phi với thành phố Marrakech nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Tunisia', 'TN', 'Quốc gia Bắc Phi nhỏ với nền văn hóa đa dạng');
INSERT INTO countries (name, code, description) VALUES ('Algeria', 'DZ', 'Quốc gia Bắc Phi có diện tích lớn');
INSERT INTO countries (name, code, description) VALUES ('Ethiopia', 'ET', 'Một trong những nền văn minh cổ nhất thế giới');
INSERT INTO countries (name, code, description) VALUES ('Ghana', 'GH', 'Quốc gia Tây Phi phát triển nhanh');
INSERT INTO countries (name, code, description) VALUES ('Uganda', 'UG', 'Quốc gia Đông Phi xanh tươi và năng động');
INSERT INTO countries (name, code, description) VALUES ('Tanzania', 'TZ', 'Nơi có núi Kilimanjaro và vườn quốc gia Serengeti');
INSERT INTO countries (name, code, description) VALUES ('Madagascar', 'MG', 'Hòn đảo lớn với hệ sinh thái độc đáo');
INSERT INTO countries (name, code, description) VALUES ('Zimbabwe', 'ZW', 'Quốc gia Nam Phi có thác Victoria nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Mozambique', 'MZ', 'Quốc gia Đông Phi ven Ấn Độ Dương');
INSERT INTO countries (name, code, description) VALUES ('Zambia', 'ZM', 'Đất nước với nhiều tài nguyên khoáng sản');
INSERT INTO countries (name, code, description) VALUES ('Angola', 'AO', 'Quốc gia giàu dầu mỏ ở châu Phi');
INSERT INTO countries (name, code, description) VALUES ('Sudan', 'SD', 'Quốc gia châu Phi với sông Nile xanh và trắng');
INSERT INTO countries (name, code, description) VALUES ('Qatar', 'QA', 'Quốc gia Trung Đông giàu có và hiện đại');
INSERT INTO countries (name, code, description) VALUES ('Kuwait', 'KW', 'Quốc gia dầu mỏ nhỏ ở Vịnh Ba Tư');
INSERT INTO countries (name, code, description) VALUES ('Oman', 'OM', 'Quốc gia Ả Rập với bờ biển dài và văn hóa cổ xưa');
INSERT INTO countries (name, code, description) VALUES ('Yemen', 'YE', 'Quốc gia có vị trí chiến lược ở bán đảo Ả Rập');
INSERT INTO countries (name, code, description) VALUES ('Iran', 'IR', 'Quốc gia Trung Đông với lịch sử hàng nghìn năm');
INSERT INTO countries (name, code, description) VALUES ('Iraq', 'IQ', 'Vùng đất của nền văn minh Lưỡng Hà cổ đại');
INSERT INTO countries (name, code, description) VALUES ('Afghanistan', 'AF', 'Quốc gia miền núi Trung Á');
INSERT INTO countries (name, code, description) VALUES ('Kazakhstan', 'KZ', 'Quốc gia lớn ở Trung Á');
INSERT INTO countries (name, code, description) VALUES ('Uzbekistan', 'UZ', 'Quốc gia Trung Á với các thành phố cổ trên Con đường Tơ Lụa');
INSERT INTO countries (name, code, description) VALUES ('Mongolia', 'MN', 'Quốc gia thảo nguyên giữa Nga và Trung Quốc');
INSERT INTO countries (name, code, description) VALUES ('North Korea', 'KP', 'Quốc gia bí ẩn ở Đông Á');
INSERT INTO countries (name, code, description) VALUES ('Taiwan', 'TW', 'Hòn đảo công nghệ phát triển mạnh');
INSERT INTO countries (name, code, description) VALUES ('Hong Kong', 'HK', 'Đặc khu hành chính sôi động của Trung Quốc');
INSERT INTO countries (name, code, description) VALUES ('Macau', 'MO', 'Đặc khu hành chính nổi tiếng với casino');
INSERT INTO countries (name, code, description) VALUES ('Panama', 'PA', 'Quốc gia Trung Mỹ với kênh đào nổi tiếng');
INSERT INTO countries (name, code, description) VALUES ('Cuba', 'CU', 'Quốc gia Caribbean với âm nhạc sôi động');
INSERT INTO countries (name, code, description) VALUES ('Jamaica', 'JM', 'Quốc gia quê hương của nhạc reggae');
